# Generated by Django 5.2 on 2025-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjob',
            name='applied',
            field=models.BooleanField(default=False),
        ),
    ]
