# Generated by Django 5.2 on 2025-06-14 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_savedjob_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedjob',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 6, 15)),
            preserve_default=False,
        ),
    ]
